# Generated by Django 3.0 on 2020-01-08 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_auto_20200108_0434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='images',
            new_name='image',
        ),
    ]
